version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.10

jobs:
  build_and_test:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build Docker images
          command: docker-compose build

      - run:
          name: Run Tests
          command: |
            # Run frontend tests
            docker-compose run --rm frontend npm test -- --watchAll=false
            # Run backend tests
            docker-compose run --rm backend python manage.py test

      - run:
          name: Start backend and frontend
          command: docker-compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - master
